services:
  app:
    image: mosqueiro/yt-manager:0.0.4
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:3000/api/auth/callback}
    volumes:
      - data:/app/data
      - images:/app/public/images
    restart: unless-stopped

volumes:
  data:
  images:
